const products = [
    {id: '1', name : "Jean Paul Gaultier EDT", img : "https://fraguru.com/mdimg/perfume/375x500.430.jpg", price: 23000, category: "masculinos", description: "Perfume Jean Paul Gaultier EDT", detail : "Le Male de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Fougère para Hombres. Le Male se lanzó en 1995. La Nariz detrás de esta fragrancia es Francis Kurkdjian. Las Notas de Salida son lavanda, menta, cardamomo, bergamota y abrótano; las Notas de Corazón son canela, flor de azahar del naranjo y alcaravea; las Notas de Fondo son vainilla, haba tonka, ámbar, sándalo y cedro."},
    {id: '2', name : "Le Male Le Parfum", img : "https://fraguru.com/mdimg/perfume/375x500.61856.jpg", price: 25000, category: "masculinos", description: "Perfume Jean Paul Gaultier EDT", detail : "Le Male Le Parfum de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar para Hombres. Esta fragrancia es nueva. Le Male Le Parfum se lanzó en 2020. Le Male Le Parfum fue creada por Quentin Bisch y Natalie Gracia-Cetto. La Nota de Salida es cardamomo; las Notas de Corazón son lavanda y iris; las Notas de Fondo son vainilla, notas orientales y notas amaderadas."},
    {id: '3', name : "Le Male Essence de Parfum", img : "https://fraguru.com/mdimg/perfume/375x500.39583.jpg", price: 25000, category: "masculinos", description: "Perfume Jean Paul Gaultier EDT", detail : "Le Male Essence de Parfum de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Fougère para Hombres. Le Male Essence de Parfum se lanzó en 2016. La Nariz detrás de esta fragrancia es Quentin Bisch. Las Notas de Salida son cardamomo, pimienta, bergamota y abrótano; las Notas de Corazón son cuero, lavanda, canela y salvia; las Notas de Fondo son vainilla, cumarina, Amberwood, almizcle y caña agria (cañuela santa)."},
    {id: '4', name : "Le Beau", img : "https://fraguru.com/mdimg/perfume/375x500.55785.jpg", price: 25000, category: "masculinos", description: "Le Beau de Jean Paul Gaultier", detail : "Le Beau de Jean Paul Gaultier es una fragancia de la familia olfativa Amaderada Aromática para Hombres. Le Beau se lanzó en 2019. Le Beau fue creada por Quentin Bisch y Sonia Constant. La Nota de Salida es bergamota; la Nota de Corazón es coco; la Nota de Fondo es haba tonka."},
    {id: '5', name : "Le Beau", img : "https://fraguru.com/mdimg/perfume/375x500.30947.jpg", price: 25000, category: "masculinos", description: "Ultra Male de Jean Paul Gaultier", detail: "Ultra Male de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Fougère para Hombres. Ultra Male se lanzó en 2015. La Nariz detrás de esta fragrancia es Francis Kurkdjian. Las Notas de Salida son pera, lavanda, menta, bergamota y limón (lima ácida); las Notas de Corazón son canela, esclarea y alcaravea; las Notas de Fondo son vaina de vainilla negra, ámbar, pachulí y cedro."},
    {id: '6', name : "Le Belle", img : "https://fraguru.com/mdimg/perfume/375x500.55786.jpg", price: 25000, category: "femeninos", description: "La Belle de Jean Paul Gaultier", detail: "La Belle de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Vainilla para Mujeres. La Belle se lanzó en 2019. La Belle fue creada por Quentin Bisch y Sonia Constant. Las Notas de Salida son pera y bergamota; las Notas de Corazón son notas florales y cuero; las Notas de Fondo son vainilla, vetiver, ámbar y almizcle."},
    {id: '7', name : "La Belle Le Parfum", img : "https://fraguru.com/mdimg/perfume/375x500.65175.jpg", price: 25000, category: "femeninos", description: "La Belle Le Parfum de Jean Paul Gaultier", detail: "La Belle Le Parfum de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Vainilla para Mujeres. Esta fragrancia es nueva. La Belle Le Parfum se lanzó en 2021. La Belle Le Parfum fue creada por Quentin Bisch y Sonia Constant. La Nota de Salida es pera; las Notas de Corazón son haba tonka y jazmín; la Nota de Fondo es vainilla."},
    {id: '8', name : "La Belle Fleur Terrible", img : "https://fraguru.com/mdimg/perfume/375x500.71822.jpg", price: 25000, category: "femeninos", description: "La Belle Fleur Terrible de Jean Paul Gaultier", detail: "La Belle Fleur Terrible de Jean Paul Gaultier es una fragancia de la familia olfativa Floral Acuática para Mujeres. Esta fragrancia es nueva. La Belle Fleur Terrible se lanzó en 2022. La Nariz detrás de esta fragrancia es Quentin Bisch. La Nota de Salida es nenúfar (lirio de agua); la Nota de Corazón es iris; la Nota de Fondo es vainilla."},
    {id: '9', name : "Scandal", img : "https://fraguru.com/mdimg/perfume/375x500.45651.jpg", price: 25000, category: "femeninos", description: "Scandal de Jean Paul Gaultier", detail: "Scandal de Jean Paul Gaultier es una fragancia de la familia olfativa Chipre Floral para Mujeres. Scandal se lanzó en 2017. Scandal fue creada por Daphné Bugey, Fabrice Pellegrin y Christophe Raynaud. Las Notas de Salida son naranja sanguina y mandarina; las Notas de Corazón son miel, gardenia, flor de azahar del naranjo, jazmín y durazno (melocotón); las Notas de Fondo son cera de abeja, caramelo, pachulí y regaliz."},
    {id: '10', name : "Scandal Le Parfum", img : "https://fraguru.com/mdimg/perfume/375x500.74914.jpg", price: 25000, category : "femeninos", description : "Scandal Le Parfum de Jean Paul Gaultier", detail : "Scandal Le Parfum de Jean Paul Gaultier es una fragancia de la familia olfativa Ámbar Floral para Mujeres. Esta fragrancia es nueva. Scandal Le Parfum se lanzó en 2022. Scandal Le Parfum fue creada por Ane Ayo, Fabrice Pellegrin y Daphné Bugey. La Nota de Salida es jazmín; las Notas de Corazón son caramelo y sal; la Nota de Fondo es vainilla."},
    {id: '11', name : "Cheer Dieciseis Set", category: 'set', size:"100ml","description":"Set perfume mujer 100ml + Body splash" , "img" : "https://pedidosfarma.vteximg.com.br/arquivos/ids/187680-1000-1000/Cher-Dieciseis-Set-Perfume-Mujer-100-Ml-Edp-Body-Splash-.jpg?v=637756095793970000", "price": 10000},
    {id: '12', name : "Tommy Hilfiger Set", category: 'set',size:"50ml","description":"Set perfume hombre 50ml + kit unisex" , "img" : "https://juleriaque.vteximg.com.br/arquivos/ids/185954-1000-1000/tommy-men-edt-E8E9037FEC0A062D392934CEA192D092.jpg?v=637890303256730000", "price": 13000},
    {id: '13', name : "Paco Rabanne Pure Xs EDP Set", category: 'set', size:"50ml","description":"Set perfume mujer 50ml + EDP 10ml" , "img" : "https://pedidosfarma.vteximg.com.br/arquivos/ids/177312-1000-1000/Paco-Rabanne-Pure-Xs-Set-Perfume-Imp-Mujer-Edt-50ml-Edp-10ml.jpg?v=637396007747830000", "price": 16000}
    ]
    
export const getProducts = (categoryId) => {
    return new Promise ((resolve) =>{
        setTimeout(()=>{
            resolve (categoryId ? products.filter(prod => prod.category === categoryId) : products)
        }, 1000)
    })
}    
export const getProduct = (id) => {
    return new Promise ((resolve) =>{
        setTimeout(()=>{
            resolve (products.find(prod => prod.id === id))
        }, 1000)
    })
}    

